name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: 0.0.0
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Gradle Wraper Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.OS }}-gradle-wraper-cache

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        env:
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
        run: ./gradlew build

      - name: Identify current version
        id: current_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'VERSION_NAME'

      - name: Write new version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'VERSION_NAME'
          value: ${{ github.event.inputs.version }}

      - name: Publish to maven central
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishToSonatype #closeSonatypeStagingRepository

#       - uses: matheusalbino/git-commit@v1.0.1
#         with:
#           user-name: ruffCode
#           user-email: alexi@ruffCode.com
#           message: bump version ${{ steps.current_version.outputs.value }} --> ${{ github.event.inputs.version }}
#           github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ github.event.inputs.version }}
          message: ${{ github.event.inputs.version.description }}
          token: ${{ secrets.GITHUB_TOKEN }}
